<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image\drive.png" />
    <None Remove="Image\forward.png" />
    <None Remove="Image\play.png" />
    <None Remove="Image\rewind.png" />
    <None Remove="Image\stop.png" />
    <None Remove="Image\volume.png" />
    <Resource Include="Image\drive.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <None Remove="Image\folder.png" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <Resource Include="Image\folder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\forward.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\play.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\rewind.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\stop.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\volume.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <None Remove="Image\track_placeholder.png" />
    <Resource Include="Image\track_placeholder.png" />
  </ItemGroup>

</Project>
