<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image\add.png" />
    <None Remove="Image\downloads.png" />
    <None Remove="Image\drive.png" />
    <None Remove="Image\edit.png" />
    <None Remove="Image\forward.png" />
    <None Remove="Image\music.png" />
    <None Remove="Image\play.png" />
    <None Remove="Image\remove.png" />
    <None Remove="Image\rewind.png" />
    <None Remove="Image\stop.png" />
    <None Remove="Image\volume.png" />
    <Resource Include="Image\add.png" />
    <Resource Include="Image\downloads.png" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
    <Resource Include="Image\drive.png" />
    <Resource Include="Image\edit.png" />
    <Resource Include="Image\forward.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\folder.png" />
    <Resource Include="Image\music.png" />
    <Resource Include="Image\play.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\remove.png" />
    <Resource Include="Image\rewind.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\stop.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\volume.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <None Remove="Image\track_placeholder.png" />
    <Resource Include="loading.gif" />
    <Resource Include="Image\track_placeholder.png" />
  </ItemGroup>

</Project>
